name: 'Game Board Movement'

on:
  push:
    branches:
      - main

jobs:
  game-movement:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r game_board/requirements.txt

    - name: Display Initial Board
      run: python game_board/game.py display

    - name: Move in Different Directions
      run: |
        python game_board/game.py move right
        python game_board/game.py display
        python game_board/game.py move down
        python game_board/game.py display
        python game_board/game.py move left
        python game_board/game.py display
        python game_board/game.py move up
        python game_board/game.py display
