name: 'Game Board Movement'

on:
  push:
    branches:
      - main

jobs:
  game-movement:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/TAU/TAU3/requirements.txt || true

    - name: Display Initial Board
      run: python $GITHUB_WORKSPACE/TAU/TAU3/main.py display

    - name: Move in Different Directions
      run: |
        python $GITHUB_WORKSPACE/TAU/TAU3/main.py move right
        python $GITHUB_WORKSPACE/TAU/TAU3/main.py display
        python $GITHUB_WORKSPACE/TAU/TAU3/main.py move down
        python $GITHUB_WORKSPACE/TAU/TAU3/main.py display
        python $GITHUB_WORKSPACE/TAU/TAU3/main.py move left
        python $GITHUB_WORKSPACE/TAU/TAU3/main.py display
        python $GITHUB_WORKSPACE/TAU/TAU3/main.py move up
        python $GITHUB_WORKSPACE/TAU/TAU3/main.py display
